version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./docker_server_conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
  db:
    depends_on:
      - php
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
      POSTGRES_USER: demo
    ports:
      - 0.0.0.0:5432:5432/tcp
  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
      - '8080:8080'
# uncomment for varnish
#  varnish:
#    image: varnish
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#    links:
#      - web
#    volumes:
#      - ./deploy/varnish/default.vcl:/etc/varnish/default.vcl
  redis:
    image: redis
    ports:
      - 6379:6379
  version: "3.2"
  services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
